
export default new Map([
["src/content/traducciones/el-problema-con-el-diseno-de-banderas.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ftraducciones%2Fel-problema-con-el-diseno-de-banderas.mdx&astroContentModuleFlag=true")],
["src/content/traducciones/el-diseno-centrado-en-las-personas.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ftraducciones%2Fel-diseno-centrado-en-las-personas.mdx&astroContentModuleFlag=true")],
["src/content/traducciones/la-autentificacion-de-tres-factores.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ftraducciones%2Fla-autentificacion-de-tres-factores.mdx&astroContentModuleFlag=true")],
["src/content/traducciones/la-psicologia-del-diseno.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ftraducciones%2Fla-psicologia-del-diseno.mdx&astroContentModuleFlag=true")],
["src/content/traducciones/la-comunicacion-mas-corta-de-la-historia.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ftraducciones%2Fla-comunicacion-mas-corta-de-la-historia.mdx&astroContentModuleFlag=true")],
["src/content/traducciones/sobre-inteligencia-artificial.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ftraducciones%2Fsobre-inteligencia-artificial.mdx&astroContentModuleFlag=true")],
["src/content/traducciones/de-la-industria-textil-a-la-luna.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ftraducciones%2Fde-la-industria-textil-a-la-luna.mdx&astroContentModuleFlag=true")],
["src/content/traducciones/el-ancho-de-banda-de-la-conciencia.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ftraducciones%2Fel-ancho-de-banda-de-la-conciencia.mdx&astroContentModuleFlag=true")],
["src/content/traducciones/licencia.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ftraducciones%2Flicencia.mdx&astroContentModuleFlag=true")]]);
		